Repository PerigonGames/Laz, pull requests merged in 2021-06, with the labels that each got.

#45 Feature/obstacle that kills
  Assets/_Laz/Placeholder/PlaceHolderKillWall.mat
  Assets/_Laz/Placeholder/PlaceHolderKillWall.mat.meta
  Assets/_Laz/Prefabs/Laz.prefab
  Assets/_Laz/Prefabs/LazKillerWall.prefab
  Assets/_Laz/Prefabs/LazKillerWall.prefab.meta
  Assets/_Laz/Scenes/Gym.unity
  Assets/_Laz/Scenes/TemplateSandbox.unity
  Assets/_Laz/Scripts/Data/Tags.cs
  Assets/_Laz/Scripts/Environment/Obstacle.cs
  Assets/_Laz/Scripts/Environment/Obstacle.cs.meta
  Assets/_Laz/Scripts/Laz/LazCoordinatorBehaviour.cs
  Assets/_Laz/Scripts/Managers/WorldManager.cs
Labels: enhancement

#47 Feature/laz 121 add autosquash action
  .github/pull_request_template.md
  .github/workflows/autosquash.yml
Labels: autosquash

#49 LAZ-123: Lazo Polish
  Assets/_Laz/Scenes/Gym.unity
  Assets/_Laz/Scripts/Lazo/Lazo.Wall.cs
  Assets/_Laz/Scripts/Lazo/Lazo.cs
  Assets/_Laz/Scripts/Lazo/LazoBehaviour.cs
  Assets/_Laz/Scripts/Lazo/LazoPosition.cs
  Assets/_Laz/Tests/Mocks/MockWorldManager.cs
Labels: autosquash

#50 Editor/patrol handles
  Assets/_Laz/Editor/PatrolLocationHandler.cs
  Assets/_Laz/Editor/PatrolLocationHandler.cs.meta
  Assets/_Laz/Scenes/TemplateSandbox.unity
  Assets/_Laz/Scenes/TestingScenes/PatrolTests.unity
  Assets/_Laz/Scripts/Environment/PatrolBehaviour.cs
Labels: Editor, autosquash

#52 Fix/MaterialColors
  Assets/_Laz/Art/LazModel/Laz.mat
  Assets/_Laz/Placeholder/PlaceHolderDoor.mat
  Assets/_Laz/Placeholder/PlaceHolderWall.mat
Labels: autosquash
