Repository PerigonGames/Laz, pull requests merged in 2021-08, with the labels that each got.

#73 Gursaanj/laz 164
  Assets/_Laz/Prefabs/Debug.meta
  Assets/_Laz/Prefabs/Debug/DebugUI.prefab
  Assets/_Laz/Prefabs/Debug/DebugUI.prefab.meta
  Assets/_Laz/Scenes/Gym.unity
  Assets/_Laz/Scenes/TemplateSandbox.unity
  Assets/_Laz/Scripts/Managers/WorldManager.cs
  Assets/_Laz/Scripts/UserInterface/DebugBehaviour.meta
  Assets/_Laz/Scripts/UserInterface/DebugBehaviour/DebugSceneChanger.cs
  Assets/_Laz/Scripts/UserInterface/DebugBehaviour/DebugSceneChanger.cs.meta
  Assets/_Laz/Scripts/UserInterface/DebugBehaviour/DebugUIBehaviour.KeyHandler.cs
  Assets/_Laz/Scripts/UserInterface/DebugBehaviour/DebugUIBehaviour.KeyHandler.cs.meta
  Assets/_Laz/Scripts/UserInterface/DebugBehaviour/DebugUIBehaviour.cs
  Assets/_Laz/Scripts/UserInterface/DebugBehaviour/DebugUIBehaviour.cs.meta
  Assets/_Laz/Scripts/UserInterface/DebugUIBehaviour.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: Editor

#75 Added Checkpoints
  Assets/_Laz/Scenes/Gym.unity
Labels: enhancement

#74 LAZ-166: AI Chomper agro behaviour
  Assets/_Laz/Materials/Lazo/Trail/FakeLazoTrail.mat
  Assets/_Laz/Materials/Lazo/Trail/FakeLazoTrail.mat.meta
  Assets/_Laz/Prefabs/AI/Chomper_Agent.prefab
  Assets/_Laz/Prefabs/Lazo/FakeLazoLine.prefab
  Assets/_Laz/Scenes/Gym.unity
  Assets/_Laz/Scenes/TemplateSandbox.unity
  Assets/_Laz/Scripts/AI/AIChomperAgro.cs
  Assets/_Laz/Scripts/AI/AIDetectionBehaviour.cs
  Assets/_Laz/Scripts/AI/ChomperBehaviour.cs
  Assets/_Laz/Scripts/AI/EnemyBehaviour.cs
  Assets/_Laz/Scripts/Lazo/FakeLazo/FakeLazo.cs
  Assets/_Laz/Scripts/Lazo/FakeLazo/FakeLazoBehaviour.cs
  Assets/_Laz/Scripts/Lazo/Lazo.FakeLazo.cs
  Assets/_Laz/Scripts/Lazo/Lazo.FakeLazo.cs.meta
  Assets/_Laz/Scripts/Lazo/Lazo.Wall.cs
  Assets/_Laz/Scripts/Lazo/Lazo.cs
  Assets/_Laz/Scripts/Lazo/LazoBehaviour.cs
  Assets/_Laz/Scripts/Lazo/LazoPosition.cs
  Assets/_Laz/Scripts/Lazo/LazoWallBehaviour.cs
  Assets/_Laz/Scripts/Managers/CheckPointManager.cs
  Assets/_Laz/Scripts/ScriptableObject/AI/Chomper.asset
  Assets/_Laz/Scripts/ScriptableObject/AI/ChomperPropertiesScriptableObject.cs
  Assets/_Laz/Scripts/ScriptableObject/AI/EnemyPropertiesScriptableObject.cs
  Assets/_Laz/Scripts/ScriptableObject/Laz/Lazo Color Gradient.asset
  Assets/_Laz/Scripts/ScriptableObject/Laz/LazoColorPropertiesScriptableObject.cs
  Assets/_Laz/Scripts/ScriptableObject/Laz/SandboxLazoProperty.asset
  Assets/_Laz/Scripts/Tools/DebugLog.cs
  Assets/_Laz/Scripts/Tools/DebugLog.cs.meta
  Assets/_Laz/Tests/Mocks/MockLazoProperties.cs
Labels: autosquash

#76 LAZ-167 - Adding post processing package
  Assets/_Laz/Scenes/Gym.unity
  Assets/_Laz/Scenes/TemplateSandbox.unity
  Assets/_Laz/Scenes/TemplateSandbox_Profiles.meta
  Assets/_Laz/Scenes/TemplateSandbox_Profiles/Main Camera Profile.asset
  Assets/_Laz/Scenes/TemplateSandbox_Profiles/Main Camera Profile.asset.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
Labels: autosquash

#77 LAZ-161: Rewriting Namespaces for tests
  Assets/_Laz/Tests/LazBoostTests.cs
  Assets/_Laz/Tests/LazDeathBoxTests.cs
  Assets/_Laz/Tests/LazModelTests.cs
  Assets/_Laz/Tests/LazMovementTests.cs
  Assets/_Laz/Tests/LazMovementsBehaviourTests.cs
  Assets/_Laz/Tests/LazoBehaviourTests.cs
  Assets/_Laz/Tests/LazoWithPlanetoidCollisionTests.cs
  Assets/_Laz/Tests/PatrolBehaviourTests.cs
  Assets/_Laz/Tests/PatrolTests.cs
  Assets/_Laz/Tests/PlanetoidPuzzleTests.cs
  Assets/_Laz/Tests/PlanetoidTests.cs
Labels: autosquash

#79 Abel/LAZ-136
  Assets/_Laz/Tests/LazoWrappableManagerTests.cs
  Assets/_Laz/Tests/LazoWrappableManagerTests.cs.meta
  Assets/_Laz/Tests/Mocks/MockPlanetoidBehaviour.cs
  Assets/_Laz/Tests/PlanetoidTests.cs
Labels: autosquash

#81 Working Debug UI
  Assets/_Laz/Prefabs/Debug/DebugUI.prefab
  Assets/_Laz/Scenes/Gym.unity
  Assets/_Laz/Scenes/TemplateSandbox.unity
  Assets/_Laz/Scripts/Managers/WorldManager.cs
  Assets/_Laz/Scripts/UserInterface/DebugBehaviour/DebugUIBehaviour.cs
Labels: autosquash, Editor

#80 LAZ-201: Create Electric Gate
  Assets/_Laz/Placeholder/PlaceholderElectricGate.mat
  Assets/_Laz/Placeholder/PlaceholderElectricGate.mat.meta
  Assets/_Laz/Prefabs/ElectricGate.prefab
  Assets/_Laz/Prefabs/ElectricGate.prefab.meta
  Assets/_Laz/Scenes/Gym.unity
  Assets/_Laz/Scenes/TemplateSandbox.unity
  Assets/_Laz/Scripts/Environment/ElectricGateBehaviour.cs
  Assets/_Laz/Scripts/Environment/ElectricGateBehaviour.cs.meta
Labels: autosquash

#82 LAZ-202 - Gate Flickering
  Assets/_Laz/Placeholder/PlaceholderElectricGate.mat
  Assets/_Laz/Prefabs/ElectricGate.prefab
  Assets/_Laz/Scenes/Gym.unity
  Assets/_Laz/Scripts/Environment/ElectricGate.cs
  Assets/_Laz/Scripts/Environment/ElectricGate.cs.meta
  Assets/_Laz/Scripts/Environment/ElectricGateBehaviour.cs
Labels: autosquash

#83 Set up checkpoint manager tests
  Assets/_Laz/Scenes/TestingScenes/LazCheckPointManagerTests.unity
  Assets/_Laz/Scenes/TestingScenes/LazCheckPointManagerTests.unity.meta
  Assets/_Laz/Tests/CheckpointManagerTests.cs
  Assets/_Laz/Tests/CheckpointManagerTests.cs.meta
  Assets/_Laz/Tests/Mocks/MockWorldManager.cs
Labels: autosquash
